FROM continuumio/miniconda3:latest

LABEL description="Base Image"

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y gcc g++ curl && \
    rm -rf /var/lib/apt/lists/*

RUN conda config --set always_yes yes --set changeps1 no && \
    conda config --add channels conda-forge && \
    conda update -q conda && \
    conda info -a


RUN mkdir -p workspace
COPY . /workspace
VOLUME /workspace 
WORKDIR /workspace

RUN conda env create -f /test/cp_base.yml || conda env update -f /test/cp_base.yml && \
    conda clean -a

RUN source /opt/conda/etc/profile.d/conda.sh && \
    conda activate cp_base 
    #&& \
    #python -m pip install --no-cache-dir . 

RUN source /opt/conda/etc/profile.d/conda.sh && \
    conda activate cp_base && \
    jupyter notebook --generate-config
    


RUN echo "conda activate cp_base" >> /root/.bashrc
RUN chsh -s /bin/bash

ENV SHELL "bash"

EXPOSE 8888
ENTRYPOINT ["/entrypoint.sh"]


